### ISSUE TITLE
Adding Country Code to AdressType.Combined data

### ISSUE THREAD

**Issue by neggenbe** [DevExpress-Examples/Reporting-Custom-Controls#4]
Found a little bug `Adress.cs` for the `AdressType.Combined` part, country part is not set and there is a missing line in the QR code (making it unrecognizable for bank scanners):

1. ConvertFromQRCodeDataString => Country code should be set also in AdressType.Combined

        `public override void ConvertFromQRCodeDataString(string[] rawString) {
            AddressType = rawString[0] == "K" ? AddressType.Combined
                : AddressType.Structured; //real value is empty or structured
            Name = rawString[1];
            if(AddressType == AddressType.Structured) {
                Street = rawString[2];
                BuildingNumber = rawString[3];
                PostalCode = rawString[4];
                Town = rawString[5];
                CountryCode = rawString[6];
            } else {
                AddressLine1 = rawString[2];
                AddressLine2 = rawString[3];
                // HERE => set country code as well!!!
                CountryCode = rawString[6];
            }
        }`

2. The `CountryCode` is missing line in the converter data string in `ConvertToQRCodeDataString` :

        `public override string ConvertToQRCodeDataString() {
            if(IsEmpty())
                return string.Join(Environment.NewLine, Enumerable.Range(0, 7).Select(a => string.Empty));

            if(AddressType == AddressType.Structured) {
                return string.Join(Environment.NewLine, ToChar(AddressType), Name, Street, BuildingNumber, PostalCode, Town, CountryCode);
            } else {
                // HERE => add CountryCode as last attribute (should always have the same amount of lines)
                return string.Join(Environment.NewLine, ToChar(AddressType), Name, AddressLine1, AddressLine2, string.Empty, string.Empty, CountryCode);
            }
        }`

**Comment by vasyaste** [comment]
Thank you for reaching out to us, @neggenbe. We need some additional time to review these problems. We will update this thread as soon as we make any progress on this.
