### ISSUE TITLE
QR Code ErrorCorrectionLevel should be M

### ISSUE THREAD

**Issue by neggenbe** [DevExpress-Examples/Reporting-Custom-Controls#6]
In SwissQrBillBrick.cs line 147 => add QR code correction level as

 ErrorCorrectionLevel = QRCodeErrorCorrectionLevel.M

Without this, we get an error for correction level mismatch.

Link to the verification site:
isotest.postfinance.ch

**Comment by vasyaste** [comment]
Hi @neggenbe,

Thank you for pointing out this error. We updated our code to resolve this problem.
