### ISSUE TITLE
 XRSwissQRBill designer doesn't appear correctly

### ISSUE THREAD

**Issue by MJOOasis** [DevExpress-Examples/Reporting-Custom-Controls#7]
The SwissQR  is not well displayed in the designer. It's working fine in preview mode. This bug seems to be only in the last version (2021.2).
![designer](https://user-images.githubusercontent.com/98988390/152437665-1cd308d1-c799-4790-a7ac-9efdcc45f24d.PNG)

On top of that, issues #4 and #6 seem to have reappeared.

**Comment by ZhannaGaidukova** [comment]
Hello @MJOOasis,
Thank you for reporting this issue. I noted it down and forwarded to the team. We will look at it in the future. 

Regarding those additional issues:

https://github.com/DevExpress-Examples/Reporting-Custom-Controls/issues/4 
I updated the example. Please test the changes and feel free to update that thread if you have additional questions. 

https://github.com/DevExpress-Examples/Reporting-Custom-Controls/issues/6
We will take a look at this issue and verify whether changes are required. Presently, please feel free to make required changes in your code and set `ErrorCorrectionLevel` to `QRCodeErrorCorrectionLevel.M`.

Thank you.

**Comment by ZhannaGaidukova** [comment]
A quick update regarding https://github.com/DevExpress-Examples/Reporting-Custom-Controls/issues/6: we fixed this issue, please check the updated example.
